"""

ARQUIVO APENAS PARA COMPREENSÃO DE ESTRUTURA.

EM ARQUIVOS DE NOME "constants.py" SÃO ARMAZENADOS OS VALORES ESPERADOS
QUE OCUPAM MAIS DE UMA LINHA DE CÓDIGO, COMO STRING MULTILINHA.

SEU CONTEÚDO FOI REMOVIDO POR CONTER INFORMAÇÕES SIGILOSAS, NÃO O BASTANTE
PARA SEREM ARMAZENADAS E CONTROLADAS POR AMBIANTE, MAS O SUFICIENTE PARA
QUE O SIGILO FOSSE MANTIDO.

"""
